maria/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
]

maria/dashboard/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from dashboard.views import inicioview,cursos_profesor,alumnos_profesor,jefeutp_cursos,director_profesores
from django.contrib.auth.views import logout_then_login,LoginView

urlpatterns = [
    re_path('^$',inicioview.as_view(),name="home"),
    re_path('accounts/', include('accounts.urls')),
    re_path('accounts/', include('django.contrib.auth.urls')),
    re_path('logout/',logout_then_login, name= 'logout'),
    re_path('profesor/cursos',cursos_profesor.as_view(),name='profesorcursos'),
    re_path('profesor/alumnos/(?P<id_curso>[\w\.]+)',alumnos_profesor.as_view(), name='profesoralumnos'),
    re_path('jefeutp/cursos',jefeutp_cursos.as_view(),name='jefeutpcursos'),
    re_path('director/trabajadores',director_profesores.as_view(),name='directorpersonal'),
]

maria/maria/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('dashboard.urls'))
]

maria/accounts/models.py
from django.db import models

# Create your models here.

maria/dashboard/models.py
from django.db import models
# Create your models here.

class usuario(models.Model):
    nombre_usuario=models.CharField(primary_key=True,max_length=40)
    nombre=models.CharField(max_length=40)
    apellido=models.CharField(max_length=40)
    es_profesor=models.BooleanField()
    def __str__(self):
        return self.nombre_usuario

class curso(models.Model):
    codigo=models.CharField(primary_key=True,max_length=15)
    enseñanza=models.CharField(max_length=15)
    grado=models.CharField(max_length=30)
    letra=models.CharField(max_length=15)
    profesor_jefe=models.ForeignKey(usuario,on_delete=models.PROTECT)
    def __str__(self):
        return self.codigo


class alumno(models.Model):
    id_alumno=models.CharField(primary_key=True,max_length=40)
    año_cursado=models.CharField(max_length=30)
    asistencia=models.IntegerField()
    comuna=models.CharField(max_length=30)
    edad=models.CharField(max_length=30)
    enseñanza=models.CharField(max_length=30)
    grado=models.CharField(max_length=30)
    letra_curso=models.CharField(max_length=30)
    promedio_general=models.FloatField()
    rbd=models.CharField(max_length=30)
    sexo=models.CharField(max_length=30)
    id_curso=models.ForeignKey(curso,on_delete=models.PROTECT)
    
    def __str__(self):
        return self.id_alumno

maria/accounts/views.py
from django.shortcuts import render

# Create your views here.

maria/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import curso,alumno,usuario
from django.views.generic import TemplateView,ListView

# Create your views here.

class inicioview(LoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'app/inicio.html')

class cursos_profesor(LoginRequiredMixin,ListView):
    def get(self,request,**kwargs):
        return render(request,'app/cursos_profesor.html',{'cursos_profesor':curso.objects.filter(profesor_jefe=request.user.username)})


class alumnos_profesor(LoginRequiredMixin,ListView):
    def get(self,request,**kwargs):
        codigo= kwargs["id_curso"]
        return render(request,'app/alumnos_profesor.html',{'alumnos_profe':alumno.objects.filter(id_curso=codigo)})

class jefeutp_cursos(LoginRequiredMixin,ListView):
    def get(self, request,**kwargs):
        return render(request,'app/cursos_profesor.html',{'cursos_profesor':curso.objects.all()})

class director_profesores(LoginRequiredMixin,ListView):
    def get(self, request,**kwargs):
        return render(request,'app/trabajadores.html',{'usuarios_plataforma':usuario.objects.all()})

maria/templates/app/alumnos_profesor.html
{% extends 'base/base.html' %}

{% block content%}


<table class ="table table=bordered">
    <thead>
        <tr>
            <td>ID Alumno</td>
            <td>Edad</td>
            <td>Sexo</td>
            <td>Comuna</td>
            <td>Año cursado</td>
            <td>RBD</td>
            <td>Asistencia</td>
            <td>ID Curso</td>
            <td>Enseñanza</td>
            <td>Grado</td>
            <td>Letra</td>
            <td>Promedio</td>

        </tr>
    </thead>
    <tbody>
         {% if alumnos_profe %}
         {% for contador in alumnos_profe %}
        <tr>
            <td>{{contador.id_alumno}}</td>
            <td>{{contador.edad}}</td>
            <td>{{contador.sexo}}</td>
            <td>{{contador.comuna}}</td>
            <td>{{contador.año_cursado}}</td>
            <td>{{contador.rbd}}</td>
            <td>{{contador.asistencia}}</td>
            <td>{{contador.id_curso}}</td>
            <td>{{contador.enseñanza}}</td>
            <td>{{contador.grado}}</td>
            <td>{{contador.letra_curso}}</td>
            <td>{{contador.promedio_general}}</td>       
                    
        {% endfor %}             
        {% else %}
        <h1>No hay registros </h1>

        {% endif %}
        </tbody>

</table>
{% endblock %}

maria/templates/app/cursos_profesor.html
{% extends 'base/base.html' %}

{% block content%}


<table class ="table table=bordered">
    <thead>
        <tr>
            <td>Codigo</td>
            <td>Enseñanza</td>
            <td>Grado</td>
            <td>Letra</td>
            <td>Profesor jefe</td>

        </tr>
    </thead>
    <tbody>
         {% if cursos_profesor %}
         {% for contador in cursos_profesor %}
        <tr>
            <td>{{contador.codigo}}</td>
            <td>{{contador.enseñanza}}</td>
            <td>{{contador.grado}}</td>
            <td>{{contador.letra}}</td>
            <td>{{contador.profesor_jefe}}</td>
            <td>
                <a class ="btn btn-primary btn-xs" href='profesor/alumnos/{{contador.codigo}}' >ver curso</a>
                </td>            
                    
        {% endfor %}             
        {% else %}
        <h1>No hay registros </h1>

        {% endif %}
        </tbody>

</table>
{% endblock %}

maria/templates/app/inicio.html
{% extends 'base/base.html' %}

{% block title %} 

{% endblock title %}

{% block scripts %}
{% endblock scripts %}

{% block content %}


<style> @import 'https://fonts.googleapis.com/css?family=Rubik+One';
    body, html { 
      margin: 0; 
      padding: 0; 
      height: 100%; 
      width: 100%; 
      background: #e53935;
      background: linear-gradient(to left, #e53935 , #e35d5b);
    }
    
    %test {
      position: absolute;
        content: '';
        transition: all .5s;
    }
      </style>


    <div> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp <iframe aling="middle" width="500" margin:0 display:block auto height="541.25" src="https://app.powerbi.com/reportEmbed?reportId=5d89dc58-6629-450d-831d-7abf1e4b657f&autoAuth=true&ctid=6fd48f41-af81-45a5-9c1e-e3990bc27e7c&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXNvdXRoLWNlbnRyYWwtdXMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D" frameborder="0" allowFullScreen="true"></iframe></div>


    {% if perms.dashboard.view_curso %}
    <div style="text-align: center;">
        <a href='jefeutp/cursos'class="btn btn-primary" style="position: absolute;top: 11%; height:50px; width:200px">Ver Todos los cursos</a>
    </div>
    {% endif %}
    {% if perms.dashboard.view_alumno %}
    <div style="text-align: center;">
        <a href='profesor/cursos' class="btn btn-primary" style="position: absolute;top: 30%; height:50px; width:200px">Ver mis cursos</a>
    </div>
    {% endif %}
    {% if perms.dashboard.view_usuario %}
    <div style="text-align: center;">
        <a href='director/trabajadores' class="btn btn-primary" style="position: absolute;top: 50%; height:50px; width:200px">Ver Trabajadores</a>
    </div>
    {% endif %}
    {% if perms.dashboard.view_usuario %}
    <div style="text-align: center;">
        <a href='jefeutp/cursos' class="btn btn-primary" style="position: absolute;top: 70%; height:50px; width:200px;color:azure">Ver todos los cursos</a>
    </div>
    {% endif %}
    


{% endblock content %}

maria/templates/app/trabajadores.html
{% extends 'base/base.html' %}

{% block content%}


<table class ="table table=bordered">
    <thead>
        <tr>
            <td>Nombre usuario </td>
            <td>Nombre </td>
            <td>Apellido</td>
            <td>Es profesor?</td>


        </tr>
    </thead>
    <tbody>
         {% if usuarios_plataforma %}
         {% for contador in usuarios_plataforma %}
        <tr>
            <td>{{contador.nombre_usuario}}</td>
            <td>{{contador.nombre}}</td>
            <td>{{contador.apellido}}</td>
            <td>{{contador.es_profesor}}</td>

           
                    
        {% endfor %}             
        {% else %}
        <h1>No hay registros </h1>

        {% endif %}
        </tbody>

</table>
{% endblock %}

maria/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- semantic UI -->
    <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    
    <title>{% block title %}
      Titulo
    {% endblock title %}</title>
    <div>
      {% block navbar %}
      <div class="container" height="5" width="5">
      <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
      <script src="{% static 'js/jquery-1.10.2.min.js'%}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                 <nav class="navbar navbar-default">
                     <div class="container-fluid">
                        <div class="navbar-header">
                          <a class="navbar-brand" href="#">Home</a>
                        </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                         <ul class="nav navbar-nav">
                            <li class="dropdown">
                              {% if perms.dashboard.view_curso %}
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Jefe UTP <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                <li><a href='jefeutp/cursos'>Todos los cursos</a></li>
                              </ul>
                              {% endif %}
                            </li>
                            <li class="dropdown">
                              {% if perms.dashboard.view_alumno %}
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Profesor<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">

                                 <li><a href='profesor/cursos'>Mis cursos</a></li>
                              </ul>
                              {% endif %}

                             </li>
                            <li class="dropdown">
                              {% if perms.dashboard.view_usuario %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Director <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">

                                <li><a href='director/trabajadores'>Profesores</a></li>

                                <li><a href='jefeutp/cursos'>Cursos</a></li>
                                </ul>
                                {% endif %}  
                            </li>
                        </ul>
                         <ul class="nav navbar-nav navbar-right">
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{user.username}}<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="/logout">Cerrar sesión</a></li>
                              </ul>
                            </li>
                         </ul>
                        </div>
                    </div>
                </nav>
            </div>
              </div>
          </div>
      </div>
    </div><!--container-->
   {% endblock navbar %}
    </div>
  </head>

  <body>
    
    {% block scripts %}  
    {% endblock scripts %}

    {% block content %}
    {% endblock content %}
    
  </body>
</html>